version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: tripuser
      POSTGRES_PASSWORD: trippass
      POSTGRES_DB: tripdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://tripuser:trippass@postgres:5432/tripdb
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  postgres_data: 